[INKLB-001] network: sessions factory: add websocket factory
cpp-park-vk-education/2023_1_The_Loopers pull request #12
Opened 2023-05-14 08:01 UTC by sonofR9

https://trello.com/c/ut2UBOUs/32-b-002-session-factory-websocket

2023-05-17 18:55 UTC, Arugaf requested changes
Нужно подлить ci.

Второй ревьюер?

2023-05-17 18:55 UTC, Arugaf commented on backend/utils/server_network/sessions_factory/include/websocket_session_factory.h
> +concept Do_ErrorCodeAndSession_Concept = requires(T&& t, boost::system::error_code ec, IServiceSession* session) {
Часть писал в другом PR. Продублирую и тут про названия, указатели...

2023-05-17 18:55 UTC, Arugaf commented on backend/utils/server_network/sessions_factory/include/websocket_session_factory.h
> +using Fun_ErrorCode = std::function<void(boost::system::error_code)>;
Алиасы в хедере - такое себе.

2023-05-17 18:55 UTC, Arugaf commented on backend/utils/server_network/sessions_factory/include/websocket_session_factory.h
> +using Fun_ErrorCode = std::function<void(boost::system::error_code)>;
Какое-то смешение стилей в названиях получилось?

2023-05-19 02:08 UTC, kingjoram reviewed
я не знаю, дают ли эти ревью хоть что-то...

2023-05-19 02:08 UTC, kingjoram commented on backend/utils/server_network/sessions_factory/src/websocket_session_factory.cpp
> +} // namespace inklink::server_network
мб я пропустил, мы без пустой строки?

2023-05-19 02:08 UTC, kingjoram commented on backend/utils/server_network/sessions_factory/include/websocket_session_factory.h
> +} // namespace inklink::server_network
будем считать, что я просто шиз

2023-05-21 13:45 UTC, Arugaf approved these changes
Аппрув.

2023-05-21 13:45 UTC, Arugaf commented on backend/utils/server_network/sessions_factory/include/isessions_factory.h
> +
nit: лишняя пустая строка.

2023-05-21 13:45 UTC, Arugaf commented on backend/utils/server_network/sessions_factory/include/websocket_session_factory.h
> +    using tcp = boost::asio::ip::tcp;
nit: нужен модификатор доступа.

2023-05-21 19:28 UTC, merged