[INKLB-003] network: service session: add websocket session
cpp-park-vk-education/2023_1_The_Loopers pull request #13
Opened 2023-05-14 08:04 UTC by sonofR9

https://trello.com/c/UYVpXdZl/30-b-003-service-session-websocket

2023-05-16 21:35 UTC, kingjoram reviewed
ну, тут прям опять же именно докапывания, сильно ничего не увидел. некоторые названия, все-таки смущают(например template <typename T>, обычно ты прям расписывал в шаблонах)

2023-05-16 21:35 UTC, kingjoram commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +
я не уверен, как правильно называть, но думал, что там _НАЗВАНИЕ_ФАЙЛА_H_. то есть, файл с разделением через подчеркивания, значит и тут должны быть? +Сеня говорил, что желательно писать весь путь, чтобы не было повторов, если используешь ifdef(да, сейчас вспомнил, что я сам не везде это сделал).
так-то прям натянуто, но всё же

2023-05-16 21:35 UTC, kingjoram commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +#include <string>
не знаю, как у нас прописано в clang, гугловский на меня ругался, когда я include ".." ставил выше include <..>

2023-05-17 04:23 UTC, sonofR9 commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +
Да, ты прав
И просмотрел, исправлю

2023-05-17 04:24 UTC, sonofR9 commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +#include <string>
Сеня сказал, чтобы теперь так было, так что clang переделал под это

2023-05-17 19:10 UTC, Arugaf requested changes
Подлить ci.

Доку неплохо было бы добавить.

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +#include <string>
Большая мешанина в хедерах.

1. Свои;
2. Кастомные;
3. Чужие библиотеки (разные через пустую строку);
4. Стандартные;

Из либ - в угловых скобках, а не кавычках.

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +using Fun_ErrorCode = std::function<void(boost::system::error_code)>;
Не стоит использовать `using` в хедерах. В классах можно.

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +            DoOnAccept = [](error_code, IServiceSession*) {}, DoOnWrite = [](error_code) {}) noexcept;
Большое количество параметров: на разные строки все аргументы.

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/include/websocket_service_session.h
> +    std::deque<std::shared_ptr<std::string const>> m_queue;
По названиям ничего не понятно.

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +          m_ws(std::move(socket)), m_doOnRead{doOnRead}, m_doOnAccept{doOnAccept}, m_doOnWrite{doOnWrite}
Получилось нечитаемо.

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +    m_manager->RemoveSession(this);
Разве менеджер не управляет сессией? Кто еще может закончить лайфтайм сессии?

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +    // thread-safe by default.
В доку?

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +    m_ws.set_option(websocket::stream_base::timeout::suggested(beast::role_type::server));
`using`

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +                        std::string(BOOST_BEAST_VERSION_STRING) + " inklink-simultaneous-access-service");
Вторую часть в отдельную `constexpr` функцию в анонимном неймспейсе?

2023-05-17 19:10 UTC, Arugaf commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +        return;
Нужны пояснения.

2023-05-18 18:44 UTC, sonofR9 commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +    // thread-safe by default.
Когда дойду до этого  (совсем скоро)

2023-05-18 18:58 UTC, sonofR9 commented on backend/utils/server_network/service_session/src/websocket_service_session.cpp
> +                        std::string(BOOST_BEAST_VERSION_STRING) + " inklink-simultaneous-access-service");
Через define сделал. В constexpr на BOOST_BEAST_VERSION_STRING ругается "expected unqualified-id"
(при замене на строку, всё нормально становится)

2023-05-21 13:49 UTC, Arugaf approved these changes
Норм.

2023-05-21 19:29 UTC, merged