[INKLB-004] network: client session: add websocket client session (with automatic resolver)
cpp-park-vk-education/2023_1_The_Loopers pull request #14
Opened 2023-05-14 08:05 UTC by sonofR9

https://trello.com/c/nmxMk5s4/37-client-front-session

2023-05-16 21:25 UTC, kingjoram reviewed
ну, что-то написал, надеюсь поможет

2023-05-16 21:25 UTC, kingjoram commented on utils/client_connector/include/global_websocket_client_session.h
> +using Fun_ErrorCode = std::function<void(boost::system::error_code)>;
а для этого разве не нужно подключать <functional>?

2023-05-16 21:25 UTC, kingjoram commented on utils/client_connector/src/websocket_client_session.cpp
> +namespace beast = boost::beast;
здесь, наверное, какая-то задумка была, но почему бы websocket не закинуть туда же, где и net/beast?

2023-05-17 04:28 UTC, sonofR9 commented on utils/client_connector/include/global_websocket_client_session.h
> +using Fun_ErrorCode = std::function<void(boost::system::error_code)>;
Да, надо, исправлю

2023-05-17 04:29 UTC, sonofR9 commented on utils/client_connector/src/websocket_client_session.cpp
> +namespace beast = boost::beast;
Согласен

Лучше всё как раз в анонимный namespace, но забыл перенести

2023-05-17 19:15 UTC, Arugaf requested changes
По стандарту: подлить ci.

Вообще те же самые замечания, что и раньше.

Доку хочу :(

2023-05-17 19:15 UTC, Arugaf commented on utils/client_connector/include/global_websocket_client_session.h
> +} // namespace inklink::client_connector
Очень странный хедер получился. Он точно нужен?

2023-05-17 19:15 UTC, Arugaf commented on utils/client_connector/src/websocket_client_session.cpp
> +    }
Ай-яй-яй...

2023-05-17 19:15 UTC, Arugaf commented on utils/client_connector/src/websocket_client_session.cpp
> +    m_close = true;
Этот метод асинхронный?

2023-05-18 20:44 UTC, sonofR9 commented on utils/client_connector/include/global_websocket_client_session.h
> +} // namespace inklink::client_connector
Одинаковые концепты в нескольких местах используются. Если я правильно понимаю, если два файла подключить с одинаково определёнными концептами, будет повторное определение?
Я не уверен, как лучше. Мне вообще не очень нравилось, что они в отдельном файле, т.к. надо далеко лезть, чтобы понять, что нужно передавать.

2023-05-18 20:46 UTC, sonofR9 commented on utils/client_connector/src/websocket_client_session.cpp
> +    }
Это чтобы приложение не падало. Пусть уж деструктор неправильно отработает и сокет не закроется/ что-нибудь ещё неприятное произойдёт, но хотя бы программа не упадёт.
Ну а если произошло что-то совсем страшное, то где-нибудь ещё успеет свалиться в течении пары минут

2023-05-18 20:50 UTC, sonofR9 commented on utils/client_connector/src/websocket_client_session.cpp
> +    m_close = true;
Да. Название не нравится?

2023-05-21 14:04 UTC, Arugaf requested changes

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/include/global_websocket_client_session.h
> +enum ConnectType
`enum class`

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/include/global_websocket_client_session.h
> +} // namespace inklink::client_connector
Можно оставить этот файл. Переименовать его в `websocket_fwd.h`.

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/include/global_websocket_client_session.h
> +concept ErrorCodeCallbackConcept = requires(T&& t, boost::system::error_code ec) {
nit: надо стараться не использовать тип (метатип) в названиях.

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/include/websocket_client_session.h
> + */
Пустая строчка.

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/include/websocket_client_session.h
> +    void Close() final;
`override` тут и во всех остальных прах.

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/src/websocket_client_session.cpp
> +    }
Да уж пусть лучше упадет, чем позволять приложению уходить в неопределенное и не предсказуемое состояние. В идеале надо обрабатывать. Оставить todo на обработку.

2023-05-21 14:04 UTC, Arugaf commented on utils/client_connector/src/websocket_client_session.cpp
> +    m_close = true;
`std::atomic` для m_close. Иначе возможен data race. Ну, в случае если кто-то еще может позвать этот метод для того же инстанса.

2023-05-21 19:39 UTC, sonofR9 commented on utils/client_connector/include/global_websocket_client_session.h
> +concept ErrorCodeCallbackConcept = requires(T&& t, boost::system::error_code ec) {
Понял
Не знал, как здесь сделать понятнее((

2023-05-21 19:40 UTC, sonofR9 commented on utils/client_connector/include/websocket_client_session.h
> +    void Close() final;
Всем вместе в фиче-ветке сделаю

2023-05-21 19:42 UTC, Arugaf approved these changes

2023-05-21 19:43 UTC, merged