[INKLB-006] network: client session: add manual websocket client session (from specific port)
cpp-park-vk-education/2023_1_The_Loopers pull request #15
Opened 2023-05-14 10:17 UTC by sonofR9

https://trello.com/c/mLaxRSWf/40-client-back-session-%D1%81-%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%80%D1%82%D0%B0

2023-05-17 19:18 UTC, Arugaf requested changes
И тут ci +общие замечания (особенно про доку :rofl:)

Ссылку на таску в человекочитаемый формат.

2023-05-17 19:18 UTC, Arugaf commented on utils/client_connector/src/manual_websocket_client_session.cpp
> +    m_host += ':' + std::to_string(port);
Почему не в одну строчку?

Вообще это бы вынес в отдельную функцию в анонимном неймспейсе.

2023-05-19 02:03 UTC, kingjoram reviewed
ну, от меня как обычно мелкие замечания

2023-05-19 02:03 UTC, kingjoram commented on utils/client_connector/CMakeLists.txt
> +    "src/manual_websocket_client_session.cpp"
не надо ли уже удалить мусорку?

2023-05-19 02:03 UTC, kingjoram commented on utils/client_connector/src/manual_websocket_client_session.cpp
> +} // namespace inklink::client_connector
в конце пустую строку потерял

2023-05-19 02:03 UTC, kingjoram commented on utils/client_connector/include/manual_websocket_client_session.h
> +#endif // _MANUAL_WEBSOCKET_CLIENT_SESSION_H_
пустая строка в конце

2023-05-19 02:03 UTC, kingjoram commented on utils/client_connector/include/manual_websocket_client_session.h
> +#endif // _MANUAL_WEBSOCKET_CLIENT_SESSION_H_
а еще не знаю, нужен ли отступ перед endif

2023-05-19 04:46 UTC, sonofR9 commented on utils/client_connector/CMakeLists.txt
> +    "src/manual_websocket_client_session.cpp"
Надо, удалю)

2023-05-19 04:47 UTC, sonofR9 commented on utils/client_connector/include/manual_websocket_client_session.h
> +#endif // _MANUAL_WEBSOCKET_CLIENT_SESSION_H_
Не уверен, но такого инклуда быть не должно

2023-05-23 08:44 UTC, Arugaf requested changes

2023-05-23 08:44 UTC, Arugaf commented on utils/client_connector/include/manual_websocket_client_session.h
> +    boost::asio::ip::tcp::socket m_socket;
Модификатор доступа на поля.

2023-05-23 08:44 UTC, Arugaf commented on utils/client_connector/src/manual_websocket_client_session.cpp
> +constexpr const char* kClientName = "inklink-client";
Excess const.

2023-05-23 08:44 UTC, Arugaf commented on utils/client_connector/src/manual_websocket_client_session.cpp
> +constexpr const char* kClientName = "inklink-client";
`constexpr std::string_view ...`

2023-05-23 19:26 UTC, sonofR9 commented on utils/client_connector/include/manual_websocket_client_session.h
> +    boost::asio::ip::tcp::socket m_socket;
Сокет здесь я вручную создаю, а потом std::move вызываю, так что const не получится.
С connectCallback и т.д. не уверен, честно говоря, будет ли оно норма работать с const
 А на остальное, вроде, тоже не выходит.

2023-05-23 20:20 UTC, Arugaf commented on utils/client_connector/include/manual_websocket_client_session.h
> +    boost::asio::ip::tcp::socket m_socket;
Модификатор доступа - это `private`/`protected`/`public`.

2023-05-23 20:24 UTC, sonofR9 commented on utils/client_connector/include/manual_websocket_client_session.h
> +    boost::asio::ip::tcp::socket m_socket;
А, туплю
Но там, вроде, всё private. Либо я не понял что-то((

2023-05-23 21:15 UTC, Arugaf approved these changes
LGTM

2023-05-25 07:15 UTC, merged