[INKLB-005] storage: file holder:
cpp-park-vk-education/2023_1_The_Loopers pull request #20
Opened 2023-05-17 00:34 UTC by kingjoram

https://trello.com/c/N0j3zhON/38-b-005-file-holder

https://github.com/cpp-park-vk-education/2023_1_The_Loopers/pull/11

2023-05-17 04:43 UTC, sonofR9 approved these changes
Очень хорошо, осталось по мелочи

2023-05-17 04:43 UTC, sonofR9 commented on backend/services/storage/include/file_holder.h
> +    virtial ~IFileHolder()
Опечатка

2023-05-17 04:43 UTC, sonofR9 commented on backend/services/storage/src/file_holder.cpp
> +    }
Можно = default

2023-05-17 04:43 UTC, sonofR9 commented on backend/services/storage/src/file_holder.cpp
> +class FileHolder : public IFileHolder
Class либо inline полностью в хэдере (т.е. как сейчас, но .h поставить), либо в хэдере объявить (как IFileHolder), а в .cpp уже реализация. Обычно используют второе, если не стремятся в header-only library, как минимум т.к. хэдер сам не собирается в object файл, а полностью включается в код. В итоге он полностью компиллируется при изменении другого файла. 

Например, есть header.h на 10000 строк с определённым в нём классом, есть file1.cpp и file2.cpp на 10 строк с включенным header.h
Изменил 1 раз одну строку в file1, компиллируется 10010 строк -- долго. Да ещё они сначала сделают это дважды: в file1 и file2

2023-05-17 04:43 UTC, sonofR9 commented on backend/services/storage/src/read_file.cpp
> +    }
\n всё равно не читается, но это не столько критично именно нам будет, вроде. 

Надо посмотреть, м.б. есть прочитать файл полностью/ что-нибудь такое

2023-05-17 19:46 UTC, Arugaf requested changes
Нужен запускающийся ci.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +    std::string Get(std::string filePath) override;
`std::filesystem`

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +    std::string Get(std::string filePath) override;
`const` на метод.

`const` на аргументы.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +class FileHolder
Кажется, что этот класс должен наследоваться от интерфейса? А где само наследование?

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/include/ifile_holder.h
> +#include "save_changes.h"
Сначала свои файлы, затем стандартные. Разделяются пустой строкой.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/include/read_file.h
> +
Много где каких-то лишних пустых строк.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/src/file_holder.cpp
> +    return false;
`return m_changesSavior.SaveFile(filePath, fileChanges);`

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +    std::string buffer;
Явные дефолтные конструкторы через `{}`.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +        return "Uncorrect file path";
Непонятно почему ошибка возвращается именно таким образом. Совсем не хорошо.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +    }
`ostream iterator`.

2023-05-17 19:46 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +}  // namespace inklink_file_holder
Везде потерялись пустые строки в конце файла.

2023-05-19 05:10 UTC, sonofR9 requested changes
В дальнейшем старайся всё же сначала пуллить/мержить изменения в ту ветку, куда открываешь pull request. Много лишних файлов и сложно смотреть изменения, относящиеся к этой ветке

И чтение файла всё же исправь

2023-05-19 05:10 UTC, sonofR9 commented on backend/services/storage/include/file_holder.h
> +namespace filesystem = std::experimental::filesystem;
Лучше внутри класса что-то вроде using filesystem::path = std::experimental::filesystem::path.

2023-05-19 05:10 UTC, sonofR9 commented on backend/services/storage/include/ifile_holder.h
> +namespace filesystem = std::experimental::filesystem;
Аналогично

2023-05-19 05:10 UTC, sonofR9 commented on backend/services/storage/src/read_file.cpp
> +    }
Сделай вот так
https://stackoverflow.com/questions/2602013/read-whole-ascii-file-into-c-stdstring

2023-05-21 14:40 UTC, Arugaf requested changes

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +using filesystem::path = std::experimental::filesystem::path;
Просто `std::filesystem`.

Можно подключить прямо тут в хедере.

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +    [[nodiscard]] const std::string Get(const std::string& filePath) override;
`std::filesystem::path`

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/include/ifile_holder.h
> +#include <experimental/filesystem>
Просто `filesystem`.

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/include/read_file.h
> +#include <experimental/filesystem>
В алфавитном порядке (тут и в остальных местах тоже).

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/include/read_file.h
> +    [[nodiscard]] const std::string GetFile(const filesystem::path& filePath) noexcept;
Без const в возвращаемом типе.

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/include/save_changes.h
> +    [[nodiscard]] bool SaveFile(const filesystem::path& filePath, const std::string& changes) noexcept;
Кажется, что тут можно обойтись и без `[[nodiscard]]`.

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +        return "Uncorrect file path";
Все еще актуально.

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +    std::stringstream buffer;
Просто дефолтные конструкторы через `{}`.

2023-05-21 14:40 UTC, Arugaf commented on backend/services/storage/src/read_file.cpp
> +    return stringFile;
`return buffer;`

2023-05-25 01:11 UTC, Arugaf requested changes

2023-05-25 01:11 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +    ReadFile m_fileReader;
Эти поля уже будут унаследованы от интерфейсного класса.

2023-05-25 01:11 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +    virtual ~FileHolder() = default;
Конкретно в этом классе можно явно не указывать.

2023-05-25 01:11 UTC, Arugaf commented on backend/services/storage/include/file_holder.h
> +    [[nodiscard]] ReadFileResult Get(const std::string& filePath) const override;
`std::filesystem::path`

2023-05-25 01:11 UTC, Arugaf commented on backend/services/storage/include/read_file.h
> +class ReadFile final
Naming: `FileReader`?

2023-05-25 01:11 UTC, Arugaf commented on backend/services/storage/include/save_changes.h
> +class SaveChanges final
Naming: `FileChangesSaver`?

2023-05-28 21:06 UTC, Arugaf approved these changes

2023-05-30 08:42 UTC, sonofR9 approved these changes

2023-05-30 08:45 UTC, merged