[INKLB-008] storage:database:
cpp-park-vk-education/2023_1_The_Loopers pull request #21
Opened 2023-05-17 00:35 UTC by kingjoram

https://trello.com/c/vvgpMDg6/65-b-008-database

https://github.com/cpp-park-vk-education/2023_1_The_Loopers/pull/17

2023-05-17 20:00 UTC, Arugaf requested changes
Нужен второй ревьюер.

Нужен запускающийся ci, который будет проходиться и, главное, быть централизованным (вместо добавления ветки вручную).

Форматирование надо привести в порядок.

Не буду особо сильно вдаваться в подробности работы с бд через соответствующие библиотеки. Но здесь явно не хватает санитайзинга аргументов, чтобы обеспечить какую-то защиту от sql инъекций.

Кажется, эта задачка замечательно место для тестов, которых, к сожалению, нет :(

Не в адаптере, но каком-нибудь классе выше уровне (если такой существует): мб стоит кэшировать ответы на соответствующие запросы? Там же, в частности, на основе этого кэша, осуществлять валидацию некоторых запросов, чтобы не пришлось зря ходить в базу данных.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +#include <pqxx/pqxx>
Инклюды стандартной либы и других библиотек отделяются пустой строкой.

Сначала другие либы.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +class PgSqlIDbAdapter
`I` в начало. Ну или `Base` в конце.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Insert(const std::string& insertPart, const std::string& valuesPart) = 0;
Что такое part?

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +class PgSqlIDbAdapter
Вообще все же это должен быть общий адаптер, а не привязанный к постгресу.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Connect(const std::string& connectionString) = 0;
Вероятно, хотелось бы видеть успешность выполнения соответствующей команды.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Connect(const std::string& connectionString) = 0;
Нужно пояснение.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +
Много пустых строчек.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    void InsertFile(std::string fileName, std::string login, std::string filePath);
`std::filesystem`

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    void SetAdapter(PgSqlIDbAdapter& adapter);
`explicit`

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +    void Insert(const std::string& insertPart, const std::string& valuesPart) override
Пропала разделяющая строка.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +class StorageDbAdapter : public PgSqlIDbAdapter
Почему класс объявляется в cpp файле?

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +        pqxx::work inserter(m_connection);
А его методы в теле класса?

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +            result = result + response[i][0] + "\n";
Нужно пояснение. Очень желательна документация для этого класса в принципе, которая поясняла бы некоторые моменты.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +        std::string result("");
Дефолтный коснтруктор.

2023-05-17 20:00 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +        for (int i = 0; i < response.size(); ++i)
`for (const auto& 'имя какое-нибудь' : response)...`

2023-05-18 13:28 UTC, kingjoram commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Insert(const std::string& insertPart, const std::string& valuesPart) = 0;
Это часть SQL запроса(например: SELECT selectPart FROM fromPart...)

2023-05-18 13:28 UTC, kingjoram commented on backend/utils/db_adapter/include/idb_adapter.h
> +class PgSqlIDbAdapter
у нас либа именно для постгреса

2023-05-18 13:33 UTC, kingjoram commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Connect(const std::string& connectionString) = 0;
а надо ли? просто если что-то идёт не так, то, вроде, они исключение кидают, которое уже у нас будет обрабатываться(но выше)

2023-05-18 13:34 UTC, kingjoram commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Connect(const std::string& connectionString) = 0;
пояснение к чему? что делают методы или пояснение к названию аргументов?

2023-05-18 13:35 UTC, kingjoram commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    void InsertFile(std::string fileName, std::string login, std::string filePath);
а это к чему? я пока так и не особо разобрался с этим filesystem, но он похоже, просто для работы с файлами. ладно его в fileHolder использовать, но тут зачем? это же хранение пути к файлу в БД

2023-05-18 14:39 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +class PgSqlIDbAdapter
Не имеет значения, должен предоставляться общий интерфейс, в который можно подсунуть нужную реализацию.

По сути нарушает принцип инверсии зависимостей.

2023-05-18 14:41 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Insert(const std::string& insertPart, const std::string& valuesPart) = 0;
Опять привязываемся к конкретной реализации (что это реляционная база данных с использованием SQL для запросов). Я бы отходил от этого, как и от специфичных названий методов. Своя мини ORM по сути.

2023-05-18 14:44 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Connect(const std::string& connectionString) = 0;
Вроде? Надо точно убедиться. Если есть решение полагаться на исключения, то все равно необходимо убедиться, что приложение не покрашиться в случае какого-нибудь невалидного запроса.

2023-05-18 14:45 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual void Connect(const std::string& connectionString) = 0;
Что делает метод, что за `connectionString`. Документацию бы добавить.

2023-05-18 14:46 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    void InsertFile(std::string fileName, std::string login, std::string filePath);
Как минимум `std::filesystem::path` для соответствующих полей.

2023-05-18 14:54 UTC, kingjoram commented on backend/utils/db_adapter/include/idb_adapter.h
> +class PgSqlIDbAdapter
то есть нужен интерфейс в целом для Бд адаптеров, от которого наследуется интерфейс для постгр, от которого наследуется уже конкретно мой? звучит как-то так себе

2023-05-19 05:36 UTC, sonofR9 requested changes
Главное: Get должен возвращать по структуре массив списка аттрибутов (vector<vecotr<attribute>>)

И в if проверь условия

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_adapter.h
> +class StorageDbAdapter : public DbAdapterBase
Сеня предложил final делать

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    explicit void SetAdapter(PgSqlIDbAdapter& adapter);
Указывается base класс

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    std::string GetGraphArcs(std::string vertexName, std::string login);
Наверное, [[nodiscard]] ... const

На const переделать обычно время уходит, как хочешь. 
nodiscard просто дописать

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    std::string GetGraphArcs(std::string vertexName, std::string login);
const std::string&

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    void InsertGraphArc(std::string fromFileName, std::string toFileName, std::string login);
const string&

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +std::string StorageDbAdapter::Select(const std::string& request)
В base было Get?

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/include/idb_adapter.h
> +    virtual std::string Get(const std::string& request) = 0;
Должен быть по смыслу массив массивов. Иначе чрезвычайно неудобно пользоваться. 

В идеале массив массивов эквивалента std::variant, но это ладно (у которого ещё доступ по названию аттрибут есть).

Вот в pqxx пользоваться удобно:
pqxx::result r{txn.exec("SELECT name, salary FROM Employee")}; 
for (auto row: r) 
std::cout // Address column by name. Use c_str() to get C-style string. 
<< row["name"].c_str() 
<< " makes " // Address column by zero-based index. Use as<int>() to parse as int. 
<< row[1].as<int>() 
<< "." 
<< std::endl;

Хочется хотя бы чтобы можно было итерироваться по строкам и внутри них по аттрибутам.

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +        result = result + response[iterator][0] + "\n";
Просто iterator[0]
И желательно не итератор, а row или что-то ещё понятное. Для маленького скопа можно, конечно, просто it, но row лучше, как по мне

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +        result = result + response[iterator][0] + "\n";
О чём и речь: захочу хранить в postgresql текст от пользователя (текущие изменения), напишет он там /n и как мне твой результат парсить?
И почему вообще я его должен парсить?

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +}
if не нужен

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +    if (!fileName && !login)
Явно не так: нет логина => делаем?
И для стрингов empty.

2023-05-19 05:36 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +    if (!vertexName && !login)
Аналогично

2023-05-20 22:53 UTC, sonofR9 reviewed
Как по мне, в таком формате пока что алиасы лучше будут, чем класс для Table. Если его полноценно делать, то класс, конечно, будет более классным, но пока что он обрезает возможности вектора без добавления своих. Ну а заменить алиас на класс в дальнейшем можно.

2023-05-20 22:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/table_after_select.h
> +struct TableAfterSelect
Мне название не нравится

2023-05-20 22:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/table_after_select.h
> +struct TableAfterSelect
Если делать так, то очень желательно итератор добавить для класса

2023-05-20 22:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/table_after_select.h
> +    [[nodiscard]] std::vector<std::string> operator[](const int iterator) const
Это не итератор, а номер строки

2023-05-20 22:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/table_after_select.h
> +struct TableAfterSelect
Мне кажется, в таком формате пока что лучше просто алиасы сделать. Класс получился урезанным вектором и ничего особо не делает относительно просто вектора.
При чём классно было бы алиас и для таблицы, и для строки. Типа 
using DbRow = std::vector<std::string>;
using DbTable = std::vector<DbRow>;
Тем более, потом алиас можно спокойно заменить на класс, по идее.

2023-05-20 22:53 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +        for (auto field : row)
const auto&

2023-05-20 22:53 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +    for (auto row: response)
const auto&

Здесь ссылка, по идее, очень может ускорить работу. Ну и в принципе.

2023-05-21 13:07 UTC, sonofR9 reviewed
Алиас только один раз в интерфейсном классе нужен
А так, вроде, всё хорошо

2023-05-21 13:07 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_adapter.h
> +using DbTable = std::vector<std::vector<std::string>>;
Алиас только один раз в интерфейсном классе нужен

2023-05-21 14:42 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +class PgSqlIDbAdapter
Нет, нужен просто интерфейс и реализация под постгрес.

2023-05-21 14:51 UTC, Arugaf requested changes

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/include/istorage_db_controller.h
> +#include <filesystem>
?

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/include/istorage_db_controller.h
> +} // namespace inklink::db_controller
Пустая строка потерялась.

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    [[nodiscard]] filesystem::path GetFilePath(std::string& fileName, std::string& login) const;
`std::filesystem::path`

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +    [[nodiscard]] filesystem::path GetFilePath(std::string& fileName, std::string& login) const;
`const std::string&`

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/include/table_after_select.h
> +} // namespace inklink::db_controller
Кажется, что в текущем состоянии, класс действительно особо ничего не делает.

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +    if (!vertexName && !sessionId)
Тут и везде: инвертировать условия, чтобы избежать лишней вложенности.

2023-05-21 14:51 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +                "SELECT filePath FROM Files WHERE fileName = '" + fileName + "' AND login = '" + login + "'";
**CRITICAL**: нужен санитайзинг аргументов. Без этого никак.

Можно оставить большущий todo, чтобы кто-нибудь еще сделал это.

2023-05-22 02:37 UTC, kingjoram commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +    if (!vertexName && !sessionId)
сделано

2023-05-22 02:43 UTC, kingjoram commented on backend/utils/db_adapter/include/table_after_select.h
> +} // namespace inklink::db_controller
временно убрал. если действительно потребуется что-то своё, то воспользуюсь. или лучше вообще пока файл этот удалить?

2023-05-23 23:53 UTC, sonofR9 requested changes
Сделай, чтобы хотя бы собиралось (ptr на connection и ещё по мелочи)

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/idb_adapter.h
> +                        const std::string& argument2) const = 0;
Что такое argument?

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/istorage_db_controller.h
> +    virtual [[nodiscard]] std::string GetAllFilesForUser(std::string& login) const = 0;
const string& login

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/storage_db_adapter.h
> +    pqxx::connection m_connection;
Сделай как минимум пока что shared_ptr/ что-нибудь, чтобы собиралось и можно было запустить. Как никак, в четверг показывать надо))

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/idb_adapter.h
> +
Лучше using в public часть класса. Тогда потом можно будет IDbAdapter::DbTable

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/istorage_db_controller.h
> +    DbAdapterBase& m_adapter;
Если ссылка, должно передаваться в конструктор.

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/table_after_select.h
> +} // namespace inklink::db_controller
Оставь пока так, чтобы видно было, что убрал пока

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +void StorageDbAdapter::Run(const std::string& connectionString)
Это dbadapter или controller должен быть?

2023-05-23 23:53 UTC, sonofR9 commented on backend/utils/db_adapter/include/idb_adapter.h
> +                        const std::string& argument2) const = 0;
Я так понял, оно конкретно для твоих сервисов только, но ладно.

2023-05-24 00:03 UTC, sonofR9 commented
И, вроде, от инъекци не защищает до конца. Типа если как argument1 передать:
* FROM _нужное_название_таблицы; DROP ...; SELECT *

В итоге валидное выражение будет. Правда, возможно, prepare не станет выполнять.

2023-05-25 01:24 UTC, Arugaf requested changes
Санитайзинга аргументов все еще нет?

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/include/idb_adapter.h
> +                        const std::string& argument2) const = 0;
Непонятно что за аргументы. Нужны более осмысленные названия.

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/include/istorage_db_controller.h
> +    virtual void Run(const std::string& connectionString) = 0;
Продублировать модификатор доступа, т.к. начинаются методы.

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_adapter.h
> +    ~StorageDbAdapter() = default;
Либо явно указать override, либо убрать.

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_adapter.h
> +    ~StorageDbAdapter() = default;
Тут тоже продублировать модификатор доступа.

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_controller.h
> +
Модификатор доступа.

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +        }
`for (const auto& ... : ...)` (в остальных местах тоже).

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +    if (!(vertexName.empty() || sessionId.empty()))
Инвертировать условия для уменьшения вложенности (во всем коде).

2023-05-25 01:24 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_adapter.cpp
> +    DbTable result;
`{}`

2023-05-28 21:34 UTC, Arugaf requested changes
В текущем пр проект просто напросто не компилится.

Надо все же либо сделать как было (с добавлением новой задачи) либо, предпочтительно, все же довести реализацию с паком параметров до конца (с использованием шаблонов).

2023-05-30 10:43 UTC, Arugaf requested changes

2023-05-30 10:43 UTC, Arugaf commented on backend/utils/db_adapter/include/istorage_db_controller.h
> +    virtual [[nodiscard]] std::string GetAllFilesForUser(const std::string& login) const = 0;
Атрибуты в начало.

2023-05-30 10:43 UTC, Arugaf commented on backend/utils/db_adapter/include/storage_db_adapter.h
> +    friend class DbAdapterBase;
Зачем?

2023-05-30 10:43 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +        return "";
`{}`

2023-05-30 10:43 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +        return "";
`{}`

2023-05-30 10:43 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +        return "";
`{}`

2023-05-30 10:43 UTC, Arugaf commented on backend/utils/db_adapter/src/storage_db_controller.cpp
> +    if (fileName.empty() || login.empty() || !filePath.empty())
В конце точно правильное условие?

2023-05-30 14:30 UTC, Arugaf submitted a review, later dismissed
LGTM

2023-05-30 22:38 UTC, sonofR9 commented on backend/utils/db_adapter/include/idb_adapter.h
> +        static_cast<Implementation*>(this)->Connect(connectionString);
Странная конструкция. Пояснишь? 
Ну или что такое Implementation

2023-05-30 22:38 UTC, sonofR9 commented on backend/utils/db_adapter/include/idb_adapter.h
> +    [[nodiscard]] std::shared_ptr<Connection> GetConnection()
Мне казалось, адаптеры обычно изолируют от конкретной реализации (например, от pqxx), но да ладно.

2023-05-30 22:41 UTC, sonofR9 approved these changes

2023-05-30 22:42 UTC, Gallaann approved these changes
LGTM

2023-05-30 22:43 UTC, merged