INKLB-009: base service chassis: logger: add splog adapter
cpp-park-vk-education/2023_1_The_Loopers pull request #23
Opened 2023-05-20 09:13 UTC by sonofR9

https://trello.com/c/CqdrTEns/77-b-009-service-chassis-logger

2023-05-21 14:56 UTC, Arugaf requested changes

2023-05-21 14:56 UTC, Arugaf commented on backend/utils/base_service_chassis/logger_adapter/include/spdlog_adapter.h
> +    void SetFile(const std::string& loggerName, const std::string& path) final;
`std::filesystem::path`

2023-05-23 20:56 UTC, Arugaf approved these changes
Ок.

2023-05-25 16:43 UTC, kingjoram approved these changes

2023-05-30 08:39 UTC, merged