Dev/a.novak/listener
cpp-park-vk-education/2023_1_The_Loopers pull request #8
Opened 2023-05-13 16:42 UTC by sonofR9

2023-05-14 23:19 UTC, Gallaann approved these changes

2023-05-17 18:06 UTC, Arugaf requested changes
Нужно ci догрузить.

Хочется видеть спецификаторы `noexcept` там, где это нужно. Возможно, `const` тоже.

Довольно сложный класс. Кажется, что тут как раз не хватает документации.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +#include <memory>
Стандартные библиотеки и остальные нужно отделять пустой строкой. Сначала идут нестандартные.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +template <DoOnAcceptConcept DoOnAccept = std::function<void(boost::system::error_code, IServiceSession*)>>
Почему указатель, а не ссылка?

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +    explicit BeastWebsocketListener(
Есть ли смысл в explicit?

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +            DoOnAccept doOnAccept = [](error_code, IServiceSession*) {});
Если уж аргументы не помещаются на одной строке (или их просто слишком много), то лучше каждый аргумент размещать на отдельной строке. Иначе плохо читается.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +            boost::asio::io_context&, const tcp::endpoint&, std::shared_ptr<ISessionsFactory>,
Разумно ли принимать `shared_ptr` на `ISessionsFactory`? Тем самым разделяется владение. Может просто ссылку?

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +    ~BeastWebsocketListener() final = default;
Предлагаю сам класс помечать как `final`, вместо его методов.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +    void Fail(error_code ec, char const* what);
Не очень понятно почему метод так называется.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +    void Fail(error_code ec, char const* what);
В данный момент этот метод явно не бросает никакое исключение. Даже если бы бросал, хотелось бы видеть скорее ссылку на `std::string` или `string_view`.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +    boost::asio::io_context& m_ioc;
Почему сокращение?

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/include/beast_websocket_listener.h
> +    DoOnAccept m_doOnAccept;
В название типа и поля хотелось бы добавить что-нибудь типа `Functor`.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/src/beast_websocket_listener.cpp
> +        : IListener(std::move(factory)), m_ioc{ioc}, m_acceptor{ioc}, m_doOnAccept{doOnAccept}
Чем обоснован `std::move` на `shared_ptr`?

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/src/beast_websocket_listener.cpp
> +        : IListener(std::move(factory)), m_ioc{ioc}, m_acceptor{ioc}, m_doOnAccept{doOnAccept}
Смешение стилей: `()` и `{}` используются в одном и том же контексте.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/src/beast_websocket_listener.cpp
> +        Fail(ec, "open");
Не очень понятно описание ошибки (справедливо для остального тоже).

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/src/beast_websocket_listener.cpp
> +    error_code ec;
Советую все же не сокращать название и тут тоже.

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/src/beast_websocket_listener.cpp
> +    }
А здесь разве как-то участвует `ec`?

2023-05-17 18:06 UTC, Arugaf commented on backend/utils/server_network/listener/src/beast_websocket_listener.cpp
> +    }
```cpp
if (m_acceptor.bind(endpoint, ec); ec) {
    Fail(ec, "bind");
    return;
}
```

2023-05-21 13:42 UTC, Arugaf approved these changes
LGTM

2023-05-21 19:18 UTC, merged