Dev/a.novak/sessions manager
cpp-park-vk-education/2023_1_The_Loopers pull request #9
Opened 2023-05-13 16:44 UTC by sonofR9

2023-05-13 17:52 UTC, Gallaann commented on back/utils/base_service_chassiss/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        throw std::logic_error(error);
Разве не ss должен пробрасыватсья в исключение? error же - пустая строка, а вот описание ошибки в ss уже

2023-05-13 18:06 UTC, Gallaann reviewed
Посмотрел

2023-05-13 18:06 UTC, Gallaann commented on back/utils/base_service_chassiss/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        throw std::logic_error(error);
Разве не ss должен пробрасыватсья в исключение? error же - пустая строка, а вот описание ошибки в ss уже

2023-05-13 18:06 UTC, Gallaann commented on back/utils/base_service_chassiss/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        users.erase(std::remove(users.begin(), users.end(), descriptor.login), users.end());
Непонятная конструкция...
Убрал всех documentId/login из мапы std::remove'ом, а потом что?

2023-05-15 14:22 UTC, Gallaann approved these changes
Немного не понял

2023-05-15 14:22 UTC, Gallaann commented on backend/utils/base_service_chassis/internal_sessions_manager/include/internal_sessions_manager.h
> +    virtual DocSessionDescriptor GetDescriptor(const Endpoint&);
С чем это связано?

2023-05-15 14:22 UTC, Gallaann commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    const std::shared_ptr<IServiceSession> sessionPtr{session};
Для чего weak указатель делать shared?

2023-05-15 21:48 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/include/internal_sessions_manager.h
> +    virtual DocSessionDescriptor GetDescriptor(const Endpoint&);
Скорее всего, класс не будет и не должен иметь других реализаций, так что он остался виртуальным только чтобы можно было заменить на stub и для тестирования

2023-05-17 18:31 UTC, Arugaf requested changes
Нужна читаемая ссылка на таску.

Нужно долить к себе запускаемый ci.

Часть комментариев к ревью распространяется на весь пр.

`[[nodiscard]]`, `noexcept`, `const` там, где это нужно.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/include/internal_sessions_manager.h
> +    virtual void RemoveSession(IServiceSession*);
Почему указатель?

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/include/internal_sessions_manager.h
> +    virtual std::vector<std::weak_ptr<IServiceSession>> GetSessionsByUser(const std::string&);
Непонятна семантика аргументов.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +#include <iservice_session.h>
Кастомные библиотеки отдельно от стандартных И идут раньше.

Бтв, почему вообще подключается так, а не через кавычки? Это другая библиотека?

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    m_DescriptorByEndpoint[endpoint] = descriptor;
Кажется, что тут лучше использовать `try_emplace` с последующей проверкой.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    m_usersByDoc[descriptor.documentId].push_back(descriptor.login);
В таком формате тут может быть вызван дефолтный конструктор. Это ожидаемое поведение? Если нет, то лучше сначала искать и обрабатывать ошибки.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    if (m_endpointByDescriptor.contains(descriptor))
Инвертировать условие.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        const Endpoint& endpoint = m_endpointByDescriptor[descriptor];
`const auto&`

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        const Endpoint& endpoint = m_endpointByDescriptor[descriptor];
Всегда ли обязательно есть соответствующий endpoint? Опять может вызываться дефолтный конструктор.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        std::erase(users, descriptor.login);
Аналогичная проблема.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    }
Ну вот да. А можно по ссылке передавать.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    const Endpoint& endpoint = session->GetClientEndpoint();
`const auto&`

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    if (m_DescriptorByEndpoint.contains(endpoint))
Опять инверсия.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        std::erase(users, descriptor.login);
Вообще вот это вот все, кажется, выглядит один в один как то, что было в методе выше. Вынести в отдельный приватный метод?

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    if (m_endpointByDescriptor.contains(descriptor))
Инверсия.

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    return result;
```cpp
    if (m_sessions.contains(endpoint))
    {
        return {m_sessions[endpoint]};
    }
```

2023-05-17 18:31 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        for (const std::string& user : m_usersByDoc[doc])
`const auto&`

2023-05-17 18:31 UTC, Arugaf commented on tests/backend/utils/base_service_chassis/internal_sessions_manager/test_internal_sessions_manager.cpp
> +} // namespace no_session
Ок.

2023-05-18 15:51 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +#include <iservice_session.h>
Да, service_session в server_network библиотеке

2023-05-18 16:06 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    m_DescriptorByEndpoint[endpoint] = descriptor;
Поставил ещё проверку m_endpointByDescriptor.contains(descriptor)
Если нет такого дескриптора, то всё остальное гарантировано будет в порядке.
И проще сначала проверить, а потом уже изменения вносить, чтобы была строгая гарантия исключений. И она здесь нужна.

2023-05-18 16:11 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    m_usersByDoc[descriptor.documentId].push_back(descriptor.login);
Да, так и надо
Правда, об ошибках в логине и documentId не думал, исправлю

2023-05-18 16:16 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        const Endpoint& endpoint = m_endpointByDescriptor[descriptor];
Здесь да, т.к. проверка до этого, а остальные существуют одновременно всегда

2023-05-18 16:17 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +        std::erase(users, descriptor.login);
Если есть в одном, то гарантированно есть во всём остальном (добавляется и удаляется всегда всё одновременно)

2023-05-18 16:29 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/include/internal_sessions_manager.h
> +    virtual void RemoveSession(IServiceSession*);
Обычно они будут по указателям (умным обычно) храниться, поэтому решил, что так извне будет удобнее пользоваться.
Если я не прав и всё равно удобнее по ссылке, то исправлю

2023-05-18 16:29 UTC, sonofR9 commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +    }
(дублирую)

Обычно они будут по указателям (умным зачастую) храниться, поэтому решил, что так извне будет удобнее пользоваться.
Если я не прав и всё равно удобнее по ссылке, то исправлю

2023-05-21 13:35 UTC, Arugaf approved these changes

2023-05-21 13:35 UTC, Arugaf commented on backend/utils/base_service_chassis/internal_sessions_manager/src/internal_sessions_manager.cpp
> +}
nit: `// namespace`

2023-05-21 19:20 UTC, merged